spring:
  # rabbitmq 配置
  rabbitmq:
    host: 192.168.10.75
    port: 5672
    virtual-host: /test
    username: test
    password: 123456
    listeners:
      simple:
        acknowledge-mode: auto # 自动ack
        retry:
          enabled: true # 开启消费者失败重试
          initial-interval: 1000ms # 初识的失败等待时长为1秒
          multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
          max-attempts: 3 # 最大重试次数
          stateless: false # true无状态；false有状态。如果业务中包含事务，这里改为false
    publisher-confirm-type: CORRELATED # 交换机的确认
    publisher-returns: true # 队列的确认
  # redis 配置
  data:
    redis:
      host: 192.168.10.75
      port: 6379
      password: 123456
      pool:
        max-active: 100
        max-idle: 10
        max-wait: -1
  # 数据库配置
  datasource:
    url: jdbc:postgresql://localhost:5432/student
    username: test
    password: 123456
  # jpa 配置
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true